### ISSUE TITLE
Calendar UI does not update immediately with newest version

### ISSUE THREAD

**Issue by Weishaupt** [arnowelzel/periodical#94]
With Version 1.70 from F-Droid I experience the following regression when entering events or mood. Once the box is ticked or unticked on returning to the main calendar view, the day is not updated (e.g. three dots on the bottom, or the heart symbol for intercourse). Only restarting the app, or switching back and fourth between Periodical and another app results in an updated calendar view.

Downgrading to 1.66 restores the correct behavior and immediately displays the correct symbol on the calendar view.

**Comment by arnowelzel** [comment]
Sorry, but I can not reproduce this. Also with release 1.70 the three dots appear immediately when I add any details to a day.

What device and Android version do you use?

**Comment by arnowelzel** [comment]
Update: I identified an issue and will provide a fix as soon as possible. It seems, that in some cases the wrong month was used for the detail dialog. This bug got introduced with 1.70 when the dialog handling was changed to use fragments.

**Comment by arnowelzel** [comment]
Fixed with https://github.com/arnowelzel/periodical/commit/9a0bee6e90dfaa3e4c8a49bc6185f2aa49ab1b63

**Comment by Weishaupt** [comment]
Great to hear. I will report back as soon, as an updated Version is released on F-Droid.

**Comment by Weishaupt** [comment]
@arnowelzel I'm on the 1.72 build from F-Droid now and still experience the same issue.

If there is anything I can do to assist you in debugging I'm happy to help.

**Comment by arnowelzel** [comment]
> @arnowelzel I'm on the 1.72 build from F-Droid now and still experience the same issue.
> 
> If there is anything I can do to assist you in debugging I'm happy to help.

That's strange - "the same issue" is logically not possible since the cause for the problem was identified and fixed. Please describe exactly how to reproduce the problem step by step.

**Comment by Weishaupt** [comment]
Steps to reproduce on my Samsung Galaxy S22+

1. Clear existing Data from the app
2. Open the app
3. Mark the current day as Period via the Edit Details dialog
4. Return to the calendar view and observe no update of the UI (if the dialogue is answered with Yes, the UI update is immediate) 
5. Schwitch back and forth between the app and another to observe an that the UI has been updated

**Comment by arnowelzel** [comment]
Hmm - that's strange. I can not reproduce it the way you describe. It works just fine (Google Pixel 6a with Android 13). So I don't know what to fix.

The error I fixed with version 1.72 was, that the date in the details dialog was wrong. So please check, if the date display in the Details page is correct. Maybe the Android version on your device behaves different. Can you tell me which Android version you are using?

**Comment by Weishaupt** [comment]
I'm also on Android 13. The issue was introduced with Version 1.70. Rolling back fixes the issue.

**Comment by arnowelzel** [comment]
And what about the date display? Is it correct in "Details"?

Also see https://github.com/arnowelzel/periodical/issues/95 and the fix in https://github.com/arnowelzel/periodical/commit/9a0bee6e90dfaa3e4c8a49bc6185f2aa49ab1b63

**Comment by Weishaupt** [comment]
The date is displayed correctly. I made a short screen recording.


https://github.com/arnowelzel/periodical/assets/2642714/0964720d-211f-4a09-8321-84c0bee918c2

**Comment by arnowelzel** [comment]
Hmm - works for me, so I am very sorry, but I don't know what to do know without debugging your device directly:


https://github.com/arnowelzel/periodical/assets/6613614/4961ccbc-5191-4c88-b1d8-a70deabe12a5

**Comment by Weishaupt** [comment]
I've tried with the APK provided from your Site. The issue remains the same. 😕 I'll have a look at the code to see if anything sparks my eyes.

**Comment by arnowelzel** [comment]
One major change in 1.70 was the introduction of fragments for dialogs - a long awaited updated to avoid dialogs to disappear when the device is rotated and thus Android restarts the main activity to reflect the layout change.

Also I updated the way how activities with results are handled since the former code was using deprecated methods. The new way is to use activity launchers and result contracts:

```
        detailsResultLauncher = registerForActivityResult(
                new ActivityResultContracts.StartActivityForResult(),
                result -> {
                    if (result.getResultCode() == Activity.RESULT_OK) {
                        handleActivityResultDetails(result.getData());
                    }
                });
```

This launcher is then used whenever the details view should be opened for a specific day:

```
    private void showDetailsActivity(int year, int month, int day) {
        Intent details = new Intent(MainActivityApp.this, DetailsActivity.class);
        details.putExtra("year", year);
        details.putExtra("month", month);
        details.putExtra("day", day);
        detailsResultLauncher.launch(details);
    }
```

As soon as the activity finishes, the result contract will be fulfilled and the registered result handler is called:

```
    protected void handleActivityResultDetails(Intent data) {
        dbMain.loadCalculatedData();
        calendarUpdate();
    }
```

This works fine on my Google Pixel 6a with Android 13, Fairphone 4 with LineageOS20, in the emulator with Android 7 and 12 and I don't see any reason why this should not work on a Samsung Galaxy S22+. The only reason - which is far fetched - I might think of: when the details activity updates the SQLite database of the app, that update is not available to the main activity since Samsung implemented some kind of caching which makes the app faster but also means that stored data is not always loaded when needed.

**Comment by jnns** [comment]
I found out that the details entered are only saved when using the left-facing arrow in the upper left corner. Using Android's backwards gesture to close the detail dialog will not save the changes. 

If this is really the underlying issue here, I think that the UX could be improved by replacing the arrow with a button with "Save" caption.

**Comment by arnowelzel** [comment]
Thanks for pointing this out.

Indeed the "arrow back" does not save. It will only trigger a local "back" action. Data will always be saved immediately when entering something in th dialog box. However when using the Android "back" gesture the app will not get notified in the same way and will not update the calendar.

You can check this: enter some details, then go back with the Android back gesture and then just switch the month in the calendar and go back, then you should see the changes.

I can reproduce that behaviour and will try to provide fix for that.

**Comment by arnowelzel** [comment]
I created a new issue for that since this issue is different to the one described here originally.

See https://github.com/arnowelzel/periodical/issues/101
